### PR TITLE
Make work on django > 2

### PR DESCRIPTION
**Pull request by yodermk**
Would be fantastic if we could get this or something like it upstream so that newer django projects can use it.  I'm very new to this project, only saw it a couple days ago, and I've only used it in 2.2, but it seems to work.  With the try/except I think it will work in < 2 also but I have not personally tried it.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @yodermk! I've created [OSPR-3662](https://openedx.atlassian.net/browse/OSPR-3662) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by yodermk** [comment]
>>> indicated your institutional affiliation

I am an employee of Rackspace, Inc.  Is that good enough?

**Comment by feanil** [comment]
@yodermk unfortunately, Rackspace is not one of the institutions that we have an agreement with so you will have to sign and send back the CLA mentioned in the above comment.  You only need to do this once and we can then review all your future code contributions. Thanks.

**Comment by natabene** [comment]
@yodermk Have you had a chance to sign the CLA mentioned above?

**Comment by natabene** [comment]
@yodermk We have not heard from you in a while, so I am closing this PR for now. Please feel free to re-open if you decide to pursue this again.

**Comment by edx-webhook** [comment]
@yodermk Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/django-config-models&entry.867055334=https://github.com/edx/django-config-models/pull/36&entry.1484655318=https://github.com/yodermk&entry.752974735=2019-06-14+14:44&entry.1917517419=2019-07-26+21:24&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
