### PR TITLE
Improve MyConfiguration code sample in README

### PR DESCRIPTION
**Pull request by dellsystem**
* Added the import line to clarify where ConfigurationModel needs to be imported from
* Fixed a typo (defalut -> default)

### CODE REVIEW

**Comment by dellsystem** [comment]
thanks @codecov-io, I was really holding my breath on that one

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dellsystem! I've created [OSPR-2890](https://openedx.atlassian.net/browse/OSPR-2890) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@dellsystem Apologies for delay. Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by natabene** [comment]
@dellsystem  Did you have a chance to sign the contributor agreement? If so, can you send it over, so we can start reviewing you code? Thanks.

**Comment by natabene** [comment]
@dellsystem I have not heard back from you so I am closing this PR now, but please feel free to reopen it in the future, should you decide to pursue this.

**Comment by edx-webhook** [comment]
@dellsystem Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/django-config-models&entry.867055334=https://github.com/edx/django-config-models/pull/6&entry.1484655318=https://github.com/dellsystem&entry.752974735=2017-04-13+16:28&entry.1917517419=2019-03-07+18:17&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
