### PR TITLE
Allow for lower versions of djangorestframework, to be compatible wit…

### PR DESCRIPTION
**Pull request by cpennington**
…h edx-platform

### CODE REVIEW

**Comment by bdero** [comment]
This is needed to unblock https://github.com/edx/edx-enterprise/pull/44. :+1:

**Comment by e-kolpakov** [comment]
@doctoryes Thank you for addressing this really quick, but could you also push a new version to pypi? It seems like 0.1.4 was not deployed to pypi: https://pypi.python.org/pypi/django-config-models/0.1.3

**Comment by doctoryes** [comment]
@e-kolpakov This PR failed tests due to some requirement versions. I have another soon-to-be-merged PR here: https://github.com/edx/django-config-models/pull/4 which will bump the version to 0.1.5 and should successfully make it to pypi.

**Comment by doctoryes** [comment]
@e-kolpakov All set now:
https://pypi.python.org/pypi/django-config-models/0.1.5

**Pull request merged**
