### PR TITLE
Add Django 1.11 support

### PR DESCRIPTION
**Pull request by bmedx**
- Updated config and tests to support Django 1.11
- Renamed tests.py so pytest actually uses it
- Add decorators.py tests

### CODE REVIEW

**Comment by doctoryes** [comment]
This is full of win!
Since this is the first dependency conversion, questions:
- Did you attempt adding Py3 to the testing mix?
- Should we be trying Py3 compatibility out in each dependency to gauge effort?
- Should an additional ticket be filed to come around post-upgrade and remove the Django 1.8/9/10 testing and requirements pinning?

**Comment by doctoryes** [comment]
Wait! Approval withdrawn until you add yourself to AUTHORS...

**Comment by bmedx** [comment]
@doctoryes 

- I took a quick stab at Python 3 support today and it looks like a non-trivial upgrade due to some unicode wrangling. Maybe 1/2 day of work? 
- It's probably worth making an attempt at Python 3 while we're updating tox, but I think that in general it would add significantly more time for each upgrade. Maybe a time-boxed attempt?
- I think for satellite repos it doesn't hurt to keep support for older versions if it's not costing us time. Personally I'd just remove them when they became a burden, but that's speaking as someone who was stuck on an old version of Django with dwindling 3rd party support for years.

**Comment by doctoryes** [comment]
@bmedx I think a time-boxed attempt makes sense - what do you think about timeboxing four hours? Also, we should keep a separate doc/spreadsheet/record of our Py3 findings as we go. Perhaps we record approximate remaining work *and/or* any significant impediments.

**Comment by doctoryes** [comment]
As far as removing < Django 1.11 support/testing, Eddie wanted to make it clear we were no longer supporting < Django 1.11 - but I'm fine with leaving the testing in until the < D1.11 testing breaks. If/When that breakage happens, we can remove the testing.

**Pull request merged**
